jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3307/classroom
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
