spring:
jpa:
  show-sql:false
hibernate:
  ddl-auto:create-drop
datasource:
  platform:postgres
  url:jdbc:postgresql://localhost:5432/classroom
  username:postgres
  password:root
  driverClassName:org.postgresql.Driver

